[package]
name = "ignisctl-rs"
version = "0.1.0"
edition = "2024"
description = "A CLI for the Ignis widget framework, written in Rust."

[dependencies]
clap = { version = "4.5.40", features = ["derive", "cargo"] }
zbus = "5.7.1"
